const bibtex = {

InvProb2025: `@Article{Marmin_A_2025_j-inv-prob_varprox_pdvpmmpsnls,
  author    = {Arthur Marmin and Fr{\'e}d{\'e}ric J.P. Richard},
  journal   = {Inverse Probl.},
  title     = {{VARPROX}: a primal-dual variable projection method for the minimization of penalized separable non-linear least squares},
  year      = {2025},
  issn      = {1361-6420},
  month     = oct,
  doi       = {10.1088/1361-6420/ae0e48},
  publisher = {IOP Publishing},
}`,

SiamSISC2025: `@Article{Krah_P_2025_j-siam-j-sci-comput_robust_spodpmdfmt,
  author    = {Philipp Krah and Arthur Marmin and Beata Zorawski and Julius Reiss and Kai Schneider},
  journal   = {SIAM J. Sci. Comput.},
  title     = {A robust shifted proper orthogonal decomposition: Proximal methods for decomposing flows with multiple transports},
  year      = {2025},
  issn      = {1095-7197},
  month     = mar,
  number    = {2},
  pages     = {A633--A656},
  volume    = {47},
  doi       = {10.1137/24m164392x},
  publisher = {Society for Industrial & Applied Mathematics (SIAM)},
}`,

TSP2023: `@Article{Marmin_A_2023_j-ieee-trans-sig-proc_majorization_msnmfbd,
  author    = {Arthur Marmin and Jos{\'{e}} Henrique de Morais Goulart and C{\'{e}}dric F{\'{e}}votte},
  journal   = {IEEE Trans. Signal Process.},
  title     = {Majorization-minimization for sparse nonnegative matrix factorization with the $\beta$-divergence},
  year      = {2023},
  month     = apr,
  pages     = {1435--1447},
  volume    = {71},
  doi       = {10.1109/tsp.2023.3266939},
  publisher = {Institute of Electrical and Electronics Engineers ({IEEE})},
}`,

SigPro2023: `@Article{Marmin_A_2023_j-sig-proc_joint-mmnmfbd,
  author    = {Arthur Marmin and Jos{\'{e}} Henrique de Morais Goulart and C{\'{e}}dric F{\'{e}}votte},
  journal   = {Signal Process.}
  title     = {Joint majorization-minimization for nonnegative matrix factorization with the $\beta$-divergence},
  year      = {2023},
  month     = aug,
  pages     = {109048},
  volume    = {209},
  doi       = {10.1016/j.sigpro.2023.109048},
  publisher = {Elsevier {BV}},
}`,

SigPro2021: `@Article{Marmin_A_2021_j-sig-proc_sparse_srnmpro,
  author    = {Arthur Marmin and Marc Castella and Jean-Christophe Pesquet and Laurent Duval},
  journal   = {Signal Process.},
  title     = {Sparse signal reconstruction for nonlinear models via piecewise rational optimization},
  year      = {2021},
  month     = feb,
  pages     = {107835},
  volume    = {179},
  doi       = {10.1016/j.sigpro.2020.107835},
  publisher = {Elsevier {BV}},
}`,

SPL2020: `@Article{Marmin_A_2020_j-ieee-sig-proc-lett_global_orcscpgn,
  author    = {Arthur Marmin and Anna Jezierska and Marc Castella and Jean-Christophe Pesquet},
  journal   = {IEEE Signal Process. Lett.},
  title     = {Global optimization for recovery of clipped signals corrupted with {P}oisson-{G}aussian noise},
  year      = {2020},
  month     = may,
  pages     = {970--974},
  volume    = {27},
  doi       = {10.1109/lsp.2020.2998699},
  publisher = {Institute of Electrical and Electronics Engineers ({IEEE})},
}`,

TSP2019: `@Article{Castella_M_2019_j-ieee-trans-sig-proc_rational_onral0p,
  author    = {Marc Castella and Jean-Christophe Pesquet and Arthur Marmin},
  journal   = {IEEE Trans. Signal Process.},
  title     = {Rational optimization for nonlinear reconstruction with approximate $\ell_0$ penalization},
  year      = {2019},
  month     = mar,
  number    = {6},
  pages     = {1407--1417},
  volume    = {67},
  doi       = {10.1109/tsp.2018.2890065},
  publisher = {Institute of Electrical and Electronics Engineers ({IEEE})},
}`,

ECCOSMAS2024: `@InProceedings{Zorawski_B_2024_p-eccomas_automated_tsnspod,
  author    = {Beata Zorawski and Shubhaditya Burela and Philipp Krah and Arthur Marmin and Kai Schneider},
  booktitle = {The 9th European Congress on Computational Methods in Applied Sciences and Engineering},
  title     = {Automated transport separation using the neural shifted proper orthogonal decomposition},
  year      = {2024},
  publisher = {CIMNE},
  doi       = {10.23967/eccomas.2024.066},
}`,

ICASSP2021: `@InProceedings{Leroy_E_2021_p-icassp_weight_itgonhnnm,
  author    = {Elie Leroy and Arthur Marmin and Marc Castella and Laurent Duval},
  booktitle = {Proc. Int. Conf. Acoust. Speech Signal Process.},
  title     = {Weight identification through global optimization in a new hysteretic neural network model},
  year      = {2021},
  month     = jun,
  pages     = {5315-5319},
  publisher = {{IEEE}},
  doi       = {10.1109/icassp39728.2021.9413383},
}`,

EUSIPCO2021: `@InProceedings{Marmin_A_2021_p-eusipco_globally_ootd,
  author    = {Arthur Marmin and Marc Castella and Jean-Christophe Pesquet},
  booktitle = {Proc. European Signal Processing Conference},
  title     = {Globally optimizing owing to tensor decomposition},
  year      = {2021},
  month     = jan,
  pages     = {990--994},
  publisher = {{IEEE}},
  doi       = {10.23919/eusipco47968.2020.9287511},
}`, 

MLSP2020:`@InProceedings{Marmin_A_2020_p-ieee-mlsp_robust_rnscpoa,
  author    = {Arthur Marmin and Marc Castella and Jean-Christophe Pesquet},
  booktitle = {IEEE Int. Workshop Mach. Learn. Signal Process.},
  title     = {Robust reconstruction with nonconvex subset constraints: A polynomial optimization approach},
  year      = {2020},
  month     = sep,
  publisher = {{IEEE}},
  doi       = {10.1109/mlsp49062.2020.9231524},
}`,

ICASSP2020: `@InProceedings{Marmin_A_2020_p-icassp_moment_bagtd,
  author    = {Arthur Marmin and Marc Castella and Jean-Christophe Pesquet},
  booktitle = {Proc. Int. Conf. Acoust. Speech Signal Process.},
  title     = {A moment-based approach for guaranteed tensor decomposition},
  year      = {2020},
  month     = may,
  pages     = {3927--3931},
  publisher = {{IEEE}},
  doi       = {10.1109/icassp40776.2020.9054186},
}`,

EUSIPCO2019: `@InProceedings{Marmin_A_2019_p-eusipco_detecting_rst,
  author    = {Arthur Marmin and Marc Castella and Jean-Christophe Pesquet},
  booktitle = {Proc. European Signal Processing Conference},
  title     = {Detecting the rank of a symmetric tensor},
  year      = {2019},
  month     = sep,
  pages     = {1--5},
  publisher = {{IEEE}},
  doi       = {10.23919/eusipco.2019.8902781},
}`,

ICASSP2019: `@InProceedings{Marmin_A_2019_p-icassp_how_gsnopialp,
  author    = {Arthur Marmin and Marc Castella and Jean-Christophe Pesquet},
  booktitle = {Proc. Int. Conf. Acoust. Speech Signal Process.},
  title     = {How to globally solve non-convex optimization problems involving an approximate $\ell_{0}$ penalization},
  year      = {2019},
  month     = may,
  pages     = {5601--5605},
  publisher = {{IEEE}},
  doi       = {10.1109/icassp.2019.8683692},
}`,

EUSIPCO2018: `@InProceedings{Marmin_A_2018_p-eusipco_signal_rsndo,
  author    = {Arthur Marmin and Marc Castella and Jean-Christophe Pesquet and Laurent Duval},
  booktitle = {Proc. European Signal Processing Conference},
  title     = {Signal reconstruction from sub-sampled and nonlinearly distorted observations},
  year      = {2018},
  month     = sep,
  pages     = {1970--1974},
  publisher = {{IEEE}},
  doi       = {10.23919/eusipco.2018.8553174},
}`,

VLSIDAT2016: `@InProceedings{Marmin_A_2016_p-vlsi-dat_architecture_aemgpud,
  author    = {Arthur Marmin and Chun-Hung Lai and Haruyuki Tago and Hsun-Lun Huang and Juin-Ming Lu},
  booktitle = {2016 International Symposium on VLSI Design, Automation and Test (VLSI-DAT)},
  title     = {Architecture agnostic energy model for {GPU}-based design},
  year      = {2016},
  month     = apr,
  pages     = {1--4},
  publisher = {IEEE},
  doi       = {10.1109/vlsi-dat.2016.7482557},
}`,

};

function downloadBibtex(id){

    const blob = new Blob(
        [bibtex[id]],
        {type:"text/plain"}
    );

    const link = document.createElement("a");

    link.href = URL.createObjectURL(blob);

    link.download = id + ".bib";

    link.click();
}
